"""Safe primitives for provisioning explicitly approved bot projects.

This module deliberately does not interpret chat text as a shell command. It
accepts only validated repository URLs, supported runtime/install profiles, and
fixed run profiles. A Telegram handler must still require an administrator's
confirmation before invoking any mutating method with ``dry_run=False``.
"""

from __future__ import annotations

import asyncio
import hashlib
import os
import re
import shutil
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from urllib.parse import urlparse

from .config import Settings, settings
from .db import Database


SLUG_RE = re.compile(r"^[a-z][a-z0-9-]{1,62}$")
ENV_NAME_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
MODULE_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_.]*$")
ENTRYPOINT_RE = re.compile(r"^[A-Za-z0-9_./-]+\.py$")
SECRET_MARKERS = ("KEY", "TOKEN", "SECRET", "PASSWORD", "PASS", "CREDENTIAL", "PRIVATE")


class BotFactoryError(ValueError):
    """Raised when a proposed managed-project operation violates policy."""


@dataclass(frozen=True)
class EnvironmentVariable:
    name: str
    required: bool = False
    secret: bool = True
    default: str = ""
    description: str = ""
    validation: str = "text"


@dataclass(frozen=True)
class ManagedProjectDraft:
    slug: str
    repository_url: str
    branch: str
    runtime: str
    run_profile: str
    run_target: str
    project_root: Path
    env_path: Path


class EnvironmentWizard:
    """Parse and render dotenv templates without retaining secret values."""

    def parse_example(self, source: Path) -> list[EnvironmentVariable]:
        if not source.exists() or not source.is_file():
            raise BotFactoryError("The selected project has no .env.example file.")
        result: list[EnvironmentVariable] = []
        description: list[str] = []
        seen: set[str] = set()
        for raw_line in source.read_text(encoding="utf-8", errors="replace").splitlines():
            line = raw_line.strip()
            if not line:
                description = []
                continue
            if line.startswith("#"):
                description.append(line.lstrip("#").strip())
                continue
            if line.startswith("export "):
                line = line[7:].strip()
            if "=" not in line:
                continue
            name, default = line.split("=", 1)
            name = name.strip()
            if not ENV_NAME_RE.fullmatch(name) or name in seen:
                description = []
                continue
            seen.add(name)
            default = default.strip().strip('"').strip("'")
            secret = any(marker in name.upper() for marker in SECRET_MARKERS)
            result.append(EnvironmentVariable(
                name=name,
                required=not bool(default),
                secret=secret,
                default=default if not secret else "",
                description=" ".join(description)[:500],
                validation=self._validation_for(name),
            ))
            description = []
        return result

    @staticmethod
    def _validation_for(name: str) -> str:
        upper = name.upper()
        if upper.endswith("_URL") or upper.endswith("_BASE"):
            return "url"
        if "PORT" in upper:
            return "integer"
        if upper.startswith(("ENABLE_", "ALLOW_", "USE_", "DEBUG_")):
            return "boolean"
        return "text"

    @staticmethod
    def _validate_value(spec: EnvironmentVariable, value: str) -> str:
        value = str(value)
        if "\x00" in value or "\n" in value or "\r" in value:
            raise BotFactoryError(f"{spec.name} must be a single line.")
        if spec.required and not value:
            raise BotFactoryError(f"{spec.name} is required.")
        if value and spec.validation == "url":
            parsed = urlparse(value)
            if parsed.scheme not in {"http", "https"} or not parsed.netloc:
                raise BotFactoryError(f"{spec.name} must be a valid HTTP(S) URL.")
        if value and spec.validation == "integer":
            try:
                int(value)
            except ValueError as exc:
                raise BotFactoryError(f"{spec.name} must be an integer.") from exc
        if value and spec.validation == "boolean" and value.lower() not in {"0", "1", "true", "false", "yes", "no", "on", "off"}:
            raise BotFactoryError(f"{spec.name} must be a boolean value.")
        return value

    def render(self, schema: list[EnvironmentVariable], supplied: dict[str, str]) -> str:
        lines = ["# Generated by Lily. Keep this file private and out of Git."]
        unknown = set(supplied) - {item.name for item in schema}
        if unknown:
            raise BotFactoryError(f"Unknown environment variable(s): {', '.join(sorted(unknown))}")
        for spec in schema:
            value = self._validate_value(spec, supplied.get(spec.name, spec.default))
            encoded = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
            lines.append(f'{spec.name}="{encoded}"')
        return "\n".join(lines) + "\n"

    def redacted_status(self, schema: list[EnvironmentVariable], supplied: dict[str, str]) -> list[dict[str, object]]:
        return [{
            "name": item.name,
            "required": item.required,
            "secret": item.secret,
            "validation": item.validation,
            "status": "configured" if bool(supplied.get(item.name, item.default)) else ("missing" if item.required else "optional"),
        } for item in schema]

    def write(self, destination: Path, schema: list[EnvironmentVariable], supplied: dict[str, str]) -> None:
        destination.parent.mkdir(parents=True, exist_ok=True)
        payload = self.render(schema, supplied)
        temporary = destination.with_suffix(destination.suffix + ".tmp")
        fd = os.open(temporary, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(payload)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary, destination)
            os.chmod(destination, 0o600)
        finally:
            if temporary.exists():
                temporary.unlink(missing_ok=True)


class ManagedBotFactory:
    """Create project plans and execute only validated, explicitly enabled steps."""

    RUNTIMES = {"python", "node", "docker-compose"}
    RUN_PROFILES = {"python-main", "python-module", "node-start", "docker-compose-up"}

    def __init__(self, database: Database, config: Settings = settings):
        self.db = database
        self.settings = config
        self.env = EnvironmentWizard()

    def _validate_repository(self, repository_url: str) -> str:
        parsed = urlparse(repository_url.strip())
        if parsed.scheme != "https" or parsed.netloc.lower() != "github.com" or len([part for part in parsed.path.split("/") if part]) != 2:
            raise BotFactoryError("Use an HTTPS GitHub repository URL in the form https://github.com/owner/repository.")
        normalized = repository_url.strip().rstrip("/")
        allowlist = self.settings.allowed_project_repositories
        if allowlist and normalized.lower() not in allowlist:
            raise BotFactoryError("This repository is not in LILY_ALLOWED_PROJECT_REPOSITORIES.")
        return normalized

    @staticmethod
    def _validate_slug(slug: str) -> str:
        normalized = slug.strip().lower()
        if not SLUG_RE.fullmatch(normalized):
            raise BotFactoryError("Project slug must use 2–63 lowercase letters, digits, or hyphens and start with a letter.")
        return normalized

    def draft(self, slug: str, repository_url: str, runtime: str, run_profile: str, run_target: str = "", branch: str = "main") -> ManagedProjectDraft:
        slug = self._validate_slug(slug)
        repository_url = self._validate_repository(repository_url)
        if runtime not in self.RUNTIMES or run_profile not in self.RUN_PROFILES:
            raise BotFactoryError("Choose one of the supported runtime and run-profile options.")
        if runtime == "python" and run_profile not in {"python-main", "python-module"}:
            raise BotFactoryError("Python projects require python-main or python-module.")
        if runtime == "node" and run_profile != "node-start":
            raise BotFactoryError("Node projects use the node-start profile.")
        if runtime == "docker-compose" and run_profile != "docker-compose-up":
            raise BotFactoryError("Docker Compose projects use the docker-compose-up profile.")
        if run_profile == "python-main" and not ENTRYPOINT_RE.fullmatch(run_target):
            raise BotFactoryError("python-main requires a relative .py entrypoint such as bot.py or app/main.py.")
        if run_profile == "python-module" and not MODULE_RE.fullmatch(run_target):
            raise BotFactoryError("python-module requires a dotted module name such as manga_bot.main.")
        if run_profile in {"node-start", "docker-compose-up"}:
            run_target = ""
        if not re.fullmatch(r"[A-Za-z0-9._/-]{1,80}", branch) or branch.startswith(("/", ".")) or ".." in branch:
            raise BotFactoryError("Branch name contains unsupported characters.")
        project_root = (self.settings.projects_root / slug).resolve()
        env_path = (self.settings.project_env_root / f"{slug}.env").resolve()
        if self.settings.projects_root.resolve() not in project_root.parents or self.settings.project_env_root.resolve() not in env_path.parents:
            raise BotFactoryError("Project paths must remain inside Lily-managed roots.")
        return ManagedProjectDraft(slug, repository_url, branch, runtime, run_profile, run_target, project_root, env_path)

    def install_plan(self, project_root: Path, runtime: str) -> list[str]:
        if runtime == "python":
            venv_python = str(project_root / ".venv" / "bin" / "python")
            if (project_root / "requirements.txt").is_file():
                return [venv_python, "-m", "pip", "install", "--no-input", "--disable-pip-version-check", "-r", "requirements.txt"]
            if (project_root / "pyproject.toml").is_file():
                return [venv_python, "-m", "pip", "install", "--no-input", "--disable-pip-version-check", "."]
            raise BotFactoryError("Python projects need requirements.txt or pyproject.toml for automatic installation.")
        if runtime == "node":
            if not (project_root / "package.json").is_file():
                raise BotFactoryError("Node projects need package.json for automatic installation.")
            return ["npm", "ci", "--ignore-scripts"]
        if runtime == "docker-compose":
            compose = next((name for name in ("compose.yml", "compose.yaml", "docker-compose.yml", "docker-compose.yaml") if (project_root / name).is_file()), None)
            if not compose:
                raise BotFactoryError("Docker projects need a Compose file.")
            return ["docker", "compose", "-f", compose, "pull"]
        raise BotFactoryError("Unsupported runtime.")

    @staticmethod
    def run_command(draft: ManagedProjectDraft) -> list[str]:
        if draft.run_profile == "python-main":
            return [str(draft.project_root / ".venv" / "bin" / "python"), draft.run_target]
        if draft.run_profile == "python-module":
            return [str(draft.project_root / ".venv" / "bin" / "python"), "-m", draft.run_target]
        if draft.run_profile == "node-start":
            return ["npm", "run", "start"]
        if draft.run_profile == "docker-compose-up":
            return ["docker", "compose", "up"]
        raise BotFactoryError("Unsupported run profile.")

    @staticmethod
    def requirements_digest(requirements: Path) -> str:
        digest = hashlib.sha256()
        with requirements.open("rb") as handle:
            for chunk in iter(lambda: handle.read(65_536), b""):
                digest.update(chunk)
        return digest.hexdigest()

    @staticmethod
    def requirements_marker(project_root: Path) -> Path:
        return project_root / ".venv" / ".requirements.sha256"

    async def _create_python_venv(self, project_root: Path) -> list[str]:
        venv_python = project_root / ".venv" / "bin" / "python"
        if venv_python.is_file():
            return [str(venv_python), "-m", "pip", "--version"]
        process = await asyncio.create_subprocess_exec(sys.executable, "-m", "venv", str(project_root / ".venv"), stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
        _, stderr = await process.communicate()
        if process.returncode != 0 or not venv_python.is_file():
            raise BotFactoryError(f"Could not create the private Python environment: {stderr.decode(errors='replace')[-300:]}")
        return [str(venv_python), "-m", "pip", "--version"]

    async def register_draft(self, draft: ManagedProjectDraft, owner_id: int) -> dict[str, object]:
        record = await self.db.register_managed_project({
            "slug": draft.slug,
            "repository_url": draft.repository_url,
            "branch": draft.branch,
            "runtime": draft.runtime,
            "run_profile": draft.run_profile,
            "run_target": draft.run_target,
            "project_root": str(draft.project_root),
            "env_path": str(draft.env_path),
            "owner_id": owner_id,
            "state": "registered",
        })
        await self.db.audit(None, owner_id, "managed_project_registered", {"slug": draft.slug, "repository_url": draft.repository_url, "runtime": draft.runtime, "run_profile": draft.run_profile})
        return record

    async def clone_and_install(self, draft: ManagedProjectDraft, *, dry_run: bool | None = None) -> dict[str, object]:
        effective_dry_run = self.settings.bot_factory_dry_run if dry_run is None else dry_run
        if effective_dry_run:
            return {"dry_run": True, "clone": ["git", "clone", "--depth", "1", "--branch", draft.branch, draft.repository_url, str(draft.project_root)], "install": "Create .venv and resolve the approved manifest after clone", "run": self.run_command(draft)}
        if draft.project_root.exists():
            raise BotFactoryError("The managed project directory already exists; use the update workflow instead.")
        draft.project_root.parent.mkdir(parents=True, exist_ok=True)
        clone = await asyncio.create_subprocess_exec("git", "clone", "--depth", "1", "--branch", draft.branch, draft.repository_url, str(draft.project_root), stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
        _, clone_error = await clone.communicate()
        if clone.returncode != 0:
            shutil.rmtree(draft.project_root, ignore_errors=True)
            raise BotFactoryError(f"Repository clone failed: {clone_error.decode(errors='replace')[-300:]}")
        if draft.runtime == "python":
            await self._create_python_venv(draft.project_root)
        install = self.install_plan(draft.project_root, draft.runtime)
        process = await asyncio.create_subprocess_exec(*install, cwd=str(draft.project_root), stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)
        _, install_error = await process.communicate()
        if process.returncode != 0:
            raise BotFactoryError(f"Dependency installation failed: {install_error.decode(errors='replace')[-300:]}")
        requirements = draft.project_root / "requirements.txt"
        if requirements.is_file():
            marker = self.requirements_marker(draft.project_root)
            marker.write_text(self.requirements_digest(requirements), encoding="utf-8")
            os.chmod(marker, 0o600)
        return {"dry_run": False, "clone": "completed", "install": install, "run": self.run_command(draft)}


bot_factory = ManagedBotFactory(Database(settings.database_url))
